---
# Labels names are important as they are used by Release Drafter to decide
# regarding where to record them in changelog or if to skip them.
#
# The repository labels will be automatically configured using this file and
# the GitHub Action https://github.com/marketplace/actions/github-labeler.
- name: breaking
  description: Breaking Changes
  color: bfd4f2
- name: bug
  description: Something isn't working
  color: d73a4a
- name: build
  description: Build System and Dependencies
  color: bfdadc
- name: ci
  description: Continuous Integration
  color: 4a97d6
- name: dependencies
  description: Pull requests that update a dependency file
  color: 0366d6
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: enhancement
  description: New feature or request
  color: a2eeef
- name: github-actions
  description: Pull requests that update Github actions code
  color: "000000"
- name: good first issue
  description: Good for newcomers
  color: 7057ff
- name: help wanted
  description: Extra attention is needed
  color: 008672
- name: invalid
  description: This doesn't seem right
  color: e4e669
- name: performance
  description: Performance
  color: "016175"
- name: python
  description: Pull requests that update Python code
  color: 2b67c6
- name: question
  description: Further information is requested
  color: d876e3
- name: refactoring
  description: Refactoring
  color: ef67c4
- name: removal
  description: Removals and Deprecations
  color: 9ae7ea
- name: style
  description: Style
  color: c120e5
- name: testing
  description: Testing
  color: b1fc6f
- name: wontfix
  description: This will not be worked on
  color: ffffff
- name: work-in-progress
  description: Work in progress that should not be auto-merged
  color: ffffff
- name: build-images
  description: Control image build on PRs
  color: fef2c0
- name: execute-workflow
  description: Control workflow execution on PRs
  color: 74da90
- name: skip-ci
  description: Skip CI workflow
  color: 35539d
- name: skip-tests
  description: Skip Tests in CI workflow
  color: 1dd225
- name: actions-debug
  description: Enable debugging in actions execution
  color: 923411
- name: workflow-mode-dev
  description: Execute workflows in dev mode (branch name for container image tags)
  color: 2085aa
