name: dnadiffusion
# this manually curated environment.yml file
# may be deprecated in favor of conda-lock.yml
# see:
#     $ poe -d conda-lock
# and pyproject.toml:
#     tool.poe.tasks.conda-lock
channels:
    - nodefaults
    - pytorch
    - nvidia
    - conda-forge
    - bioconda
dependencies:
    - python=3.10
    - accelerate
    - jupyterlab
    - matplotlib
    - pandas
    - seaborn
    - einops
    - wandb
    - scipy
    - genomepy
    - sourmash-minimal
    - bedtools
    - biopython
    - pyBigWig
    - gtfparse
    - gimmemotifs
    - pytorch
    - pytorch-cuda=12.1
    - torchvision
    - pip
    - pip:
        - tensorflow[and-cuda]
        - memory-efficient-attention-pytorch
