name: dnadiffusion
channels:
    - nodefaults
    - pytorch
    - nvidia
    - conda-forge
    - bioconda
dependencies:
    - python=3.10
    - accelerate
    - jupyterlab
    - matplotlib
    - pandas
    - seaborn
    - einops
    - wandb
    - scipy
    - genomepy
    - sourmash-minimal
    - bedtools
    - biopython
    - pyBigWig
    - gtfparse
    - gimmemotifs
    - pytorch
    - pytorch-cuda=12.1
    - torchvision
    - pip
    - pip:
        - tensorflow[and-cuda]
        - memory-efficient-attention-pytorch
