FROM python:3.10.13-slim

WORKDIR /root
ENV VENV /opt/venv
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONPATH /root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -q && \
    apt-get install -yq \
    build-essential \
    zlib1g-dev \
    swig \
    curl \
    git \
    make \
    tree \
    && rm -rf /var/lib/apt/lists/*

ENV VENV /opt/venv

RUN python3 -m venv ${VENV}
ENV PATH="${VENV}/bin:$PATH"

COPY pyproject.toml poetry.lock requirements.txt /root/

# requirements.txt auto-generated by poetry export
# see `make -n export_pip_requirements`
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . /root

# development
RUN pip install --no-deps -e .
# distribution
# RUN pip install dnadiffusion==0.1.0

ARG tag
ENV FLYTE_INTERNAL_IMAGE $tag
