defaults:
    - _self_
    - data: vanilla_sequences
    - model: dnadiffusion
    - logger: wandb
    - trainer: ddp
    - callbacks: default
    - paths: default

seed: 42
train: True
test: True
ckpt_path: null
