_target_: pytorch_lightning.Trainer

min_epochs: 1
max_epochs: 100000

accelerator: gpu
devices: 1
gradient_clip_val: 1.0
accumulate_grad_batches: 1
log_every_n_steps: 1
save_last: True
precision: 32
check_val_every_n_epoch: 1 #for debug purposes
