distributed: False
precision: "bf16"
num_workers: 2
pin_memory: True
batch_size: 120
sample_batch_size: 10
num_epochs: 5000
min_epochs: 2000
patience: 10
log_step: 50
sample_epoch: 500
number_of_samples: 1000
use_wandb: True
