name: dnadiffusion
channels:
  - nodefaults
  - conda-forge
  - bioconda
dependencies:
  - pytorch-gpu
  - torchvision
  - accelerate
  - jupyterlab
  - matplotlib
  - pandas
  - seaborn
  - einops
  - wandb
  - genomepy
  - pytorch-lightning
  - hydra-core
  - pip
  - pip:
      - gimmemotifs
      - memory-efficient-attention-pytorch
